### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by h3adex** [unknownbotcracker/Phasma-AIO#1]
Atleast they did not earned any money with this. But it is not fair to open source their work. You could have dropped some parts.

**Comment by dominuslabs** [comment]
I don't think so. These bots dont rlly work and ppl spend their hard earned money on this.

**Comment by h3adex** [comment]
> I don't think so. These bots dont rlly work and ppl spend their hard earned money on this.

@dominuslabs yes this is a good point. But there would have been more ways than just leaking the whole code.

**Comment by dominuslabs** [comment]
such as? not only did this help consumers but also devs

**Comment by h3adex** [comment]
> such as? not only did this help consumers but also devs

this code wont help anybody developing his own bot since there is way better code on github. But I see you point, would be a shame if people earn money on this. Still on the other side I am sad for this guys they got fucked so hard.
